# Architecture
arch: convmixer_1536_20

# ===== Dataset ===== #
data_url: data_url/imagenet/
set: ImageNet
num_classes: 1000
mix_up: 0.8
cutmix: 1.0
auto_augment: rand-m9-mstd0.5-inc1
interpolation: bicubic
re_prob: 0.25
re_mode: pixel
re_count: 1
mixup_prob: 1.
switch_prob: 0.5
mixup_mode: batch


# ===== Learning Rate Policy ======== #
optimizer: adamw
base_lr: 0.01
warmup_lr: 0.0001
min_lr: 0.0001
lr_scheduler: OneCycle
warmup_length: 0
nonlinearity: GELU
eps: 0.001

# ===== Network training config ===== #
amp_level: O1
keep_bn_fp32: True
beta: [ 0.9, 0.999 ]
clip_global_norm_value: 1.
is_dynamic_loss_scale: True
epochs: 150
label_smoothing: 0.1
loss_scale: 1024
weight_decay: 0.00005
momentum: 0.9
batch_size: 32
crop_pct: 0.82
print_step: 1000

# ===== Hardware setup ===== #
num_parallel_workers: 16
device_num: 8
device_target: Ascend



# ======Eval==========#
checkpoint_file_path: ./checkpoint/convmixer_1536_203-149_5004.ckpt
